### ISSUE TITLE
Doesn’t build from sdist

### ISSUE THREAD

**Issue by flying-sheep** [ralhei/pyRserve#31]
If you try to install from the source distribution hosted on PyPI, you get

```pytb
* Getting build dependencies for wheel...
Traceback (most recent call last):
  File "/usr/lib/python3.11/site-packages/pyproject_hooks/_in_process/_in_process.py", line 353, in <module>
    main()
  […]
  File "/usr/lib/python3.11/site-packages/setuptools/build_meta.py", line 338, in run_setup
    exec(code, locals())
  File "<string>", line 7, in <module>
FileNotFoundError: [Errno 2] No such file or directory: 'requirements.txt'
```

I suggest [switching to pyproject.toml](https://packaging.python.org/en/latest/tutorials/packaging-projects/) and away from setuptools to stop having to deal with its MANIFEST.in sillyness.

**Comment by ralhei** [comment]
Yes, indeed this was missing. I've added the requirement files to setup.py, no need to add a MANIFESTS files. The latest version is now 1.0.3
Thanks for reporting this problem.

**Comment by flying-sheep** [comment]
thank you!
